GestionHoraire/GestionHoraire/Controllers/AccueilController.cs
using GestionHoraire.Models;
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;

namespace GestionHoraire.Controllers
{
    public class AccueilController : Controller
    {
        public ViewResult Index()
        {
            //Cookies pour le compte du nombre de cours dans le panier
            int compteur = 0;
            if (this.Request.Cookies["nbCours"] != null)
                compteur = Convert.ToInt16(this.Request.Cookies["nbCours"]);
            else
                this.Response.Cookies.Append("nbCours", compteur.ToString());

            ViewBag.Compteur = compteur;

            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }
    }
}

GestionHoraire/GestionHoraire/Controllers/EnseignantController.cs
//Author: Samir
using GestionHoraire.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.AspNetCore.Authorization;

namespace GestionHoraire.Controllers
{
    [Authorize]
    public class EnseignantController : Controller
    {
        ILocalRepository _localRepository;
        IEnseignantRepository _enseignantRepository;
        public EnseignantController(IEnseignantRepository enseignantRepository, ILocalRepository localRepository)
        {
            _enseignantRepository = enseignantRepository;
            _localRepository = localRepository;
        }

        public ViewResult Liste()
        {
            ViewData["Title"] = "Liste des enseignants";
            return View(_enseignantRepository.ListeEnsignant);
        }

        [HttpGet]
        public ViewResult Details(int id)
        {
            Enseignants enseignant = _enseignantRepository.ListeEnsignant.FirstOrDefault(c => c.Id == id);
            return View(enseignant);
        }

        [HttpGet]
        public ViewResult Ajouter()
        {
            return View();
        }

        [HttpPost]
        public RedirectToActionResult Ajouter(Enseignants enseignant)
        {
            _enseignantRepository.Ajouter(enseignant);
            return RedirectToAction(nameof(Liste));
        }

        [HttpGet]
        public ViewResult Modifier(int id)
        {
            Enseignants enseignants = _enseignantRepository.GetEnseignant(id);

            return View(enseignants);
        }

        [HttpPost]
        public RedirectToActionResult Modifier(Enseignants enseignant)
        {
            _enseignantRepository.Modifier(enseignant);
            return RedirectToAction(nameof(Liste));
        }

        [HttpGet]
        public RedirectToActionResult Supprimer(int id)
        {
            _enseignantRepository.Supprimer(id);
            return RedirectToAction(nameof(Liste));
        }

        [HttpPost]
        public JsonResult ValiderBureauLocal(string bureau)
        {
            var local = _localRepository.ListeLocaux.FirstOrDefault(l => l.No_local == bureau);

            if (local == null)
            {
                return Json($"Le local {bureau} n'existe pas. Veuillez le créer avant de l'attribuer à l'enseignant.");
            }
            else
            {
                return Json(true);
            }
        }
    }
}

GestionHoraire/GestionHoraire/Controllers/InscriptionController.cs
//Author Jean-Francois Gamache (Fonctionnement), Samir El Haddaji (Cookies)
using GestionHoraire.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Authorization;
using System.Security.Claims;

namespace GestionHoraire.Controllers
{
    [Authorize]
    public class InscriptionController : Controller
    {
        IPanierRepository _inscriptionRepository;
        ICoursRepository _coursRepository;
        IClientRepository _clientRepository;
        
        public InscriptionController(IPanierRepository panierRepository, ICoursRepository coursRepository, IClientRepository clientRepository)
        {
            _inscriptionRepository = panierRepository;
            _coursRepository = coursRepository;
            _clientRepository = clientRepository;
        }

        /// <summary>
        /// Fonction qui permet de retourner le client connecté
        /// </summary>
        /// <returns></returns>
        public Clients GetClient()
        {
            //Récupérer le client connecté
            var idClient = User.FindFirstValue(ClaimTypes.NameIdentifier);

            Clients clientConnecte = _clientRepository.ListeClients.FirstOrDefault(c => c.UserID == idClient);
            return clientConnecte;
        }

        /// <summary>
        /// Fonction qui permet de récupérer les inscriptions d'un client
        /// </summary>
        /// <returns></returns>
        public ViewResult index()
        {
            Clients clientConnecte = GetClient();
            //Récupérer les cours du clients a partir de son ID
            var client = _inscriptionRepository.GetInscription(clientConnecte.Id);

            var viewModel = new PanierViewModel
            {
                ListeCours = client,
            };
            return View(viewModel);
        }
        
        /// <summary>
        ///  Fonction qui permet de rajouter une inscription de cours associé au client:
        /// </summary>
        /// <param name="coursId"></param>
        /// <returns></returns>
        public RedirectToActionResult AjouterAuPanier(int coursId)
        {
            //Récupérer le cours et vérifier qu'il existe.
            var cours = _coursRepository.GetCours(coursId);
            if (cours == null)
            {
                return RedirectToAction(nameof(Index));
            }

            //Récupérer le client et le rajouter à la liste des inscriptions, Si succès, incrémenter le cookie.
            Clients clientConnecte = GetClient();
            if (_inscriptionRepository.AjouterAuPanier(cours, clientConnecte))
            {
                //Cookies pour l'incrémentation du compte du nombre de cours dans le panier (@Author: Samir)
                int compteur = 0;
                if (this.Request.Cookies["nbCours"] != null)
                    compteur = Convert.ToInt16(this.Request.Cookies["nbCours"]);

                compteur++;

                this.Response.Cookies.Append("nbCours", compteur.ToString());
            }
            return RedirectToAction(nameof(Index));
        }

        /// <summary>
        /// Fonction qui récupère l'ID de l'inscription et la supprime
        /// Décremente le cookie
        /// </summary>
        /// <param name="coursId"></param>
        /// <returns></returns>
        public RedirectToActionResult SupprimerDuPanier(int coursId)
        {
            var cours = _coursRepository.GetCours(coursId);
            if (cours != null)
            {
                Clients clientConnecte = GetClient();
                _inscriptionRepository.SupprimerDuPanier(cours, clientConnecte);
            }


            //Cookies pour la décrémentation du compte du nombre de cours dans le panier (@Author: Samir)
            int compteur = 0;
            if (this.Request.Cookies["nbCours"] != null)
                compteur = Convert.ToInt16(this.Request.Cookies["nbCours"]);

            compteur--;

            this.Response.Cookies.Append("nbCours", compteur.ToString());

            return RedirectToAction(nameof(Index));
        }

        /// <summary>
        /// Fonction qui permet de supprimer toutes les inscriptions d'un client
        /// Remet le compteur du cookie à 0.
        /// </summary>
        /// <returns></returns>
        public RedirectToActionResult ViderPanier()
        {
            int compteur = 0;
            this.Response.Cookies.Append("nbCours", compteur.ToString());

            Clients clientConnecte = GetClient();
            _inscriptionRepository.ViderPanier(clientConnecte);

            return RedirectToAction(nameof(Index));
        }
    }
}

GestionHoraire/GestionHoraire/Controllers/LocalController.cs
//Auteur: Jean-Francois Gamache
using Microsoft.AspNetCore.Mvc;
using GestionHoraire.Models;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.AspNetCore.Authorization;

namespace GestionHoraire.Controllers
{
    [Authorize]
    public class LocalController : Controller
    {
        private ILocalRepository _localRepository;
        public LocalController(ILocalRepository localRepository)
        {
            _localRepository = localRepository;
        }

        /// <summary>
        /// Fonction qui apporte à la liste des locaux
        /// </summary>
        /// <returns></returns>
        public ViewResult Liste()
        {
            ViewData["Title"] = "Liste des locaux";
            return View(_localRepository.ListeLocaux);
        }

        /// <summary>
        /// Fonction qui permet permet de récupérer les détails du locaux choisi par ID
        /// </summary>
        /// <param name="id"></param>
        /// <returns></returns>
        [HttpGet]
        public ViewResult Details(int id)
        {
            Locaux local = _localRepository.GetLocal(id);
            return View(local);
        }

        /// <summary>
        /// Fonction qui apporte à la vue pour ajouter un cours
        /// </summary>
        /// <returns></returns>
        [HttpGet]
        public ViewResult Ajouter()
        {
            return View();
        }

        /// <summary>
        /// Fonction qui permet d'ajouter un local
        /// </summary>
        /// <param name="local"></param>
        /// <returns></returns>
        [HttpPost]
        public RedirectToActionResult Ajouter(Locaux local)
        {
            _localRepository.Ajouter(local);
            return RedirectToAction(nameof(Liste));
        }

        /// <summary>
        /// Fonction qui permet d'apporter a la page de modification
        /// </summary>
        /// <param name="id"></param>
        /// <returns></returns>
        [HttpGet]
        public ViewResult Modifier(int id)
        {
            Locaux local = _localRepository.GetLocal(id);

            return View(local);
        }

        /// <summary>
        /// Fonction qui permet de modifier un local
        /// </summary>
        /// <param name="local"></param>
        /// <returns></returns>
        [HttpPost]
        public RedirectToActionResult Modifier(Locaux local)
        {
            _localRepository.Modifier(local);
            return RedirectToAction(nameof(Liste));
        }

        /// <summary>
        /// Fonction qui permet de supprimer 
        /// </summary>
        /// <param name="id"></param>
        /// <returns></returns>
        [HttpGet]
        public RedirectToActionResult Supprimer(int id)
        {
            _localRepository.Supprimer(id);
            return RedirectToAction(nameof(Liste));
        }
    }
}

GestionHoraire/GestionHoraire/Views/Shared/_Layout.cshtml
<!-- Author: Samir El Haddaji et Jean-Francois Gamache -->
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - GestionHoraire</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
</head>
<body style="background-color:#242424f5;">
    <header>
        <!-- Navigation -->
        <div class="pos-f-t"><!-- Source hamburger: https://getbootstrap.com/docs/4.1/components/navbar/ -->

            <div class="collapse" id="navbarToggleExternalContent">
            </div>
            <nav class="navbar navbar-expand-lg navbar-light" style="background-color: darkslateblue;">
                <div class="container-fluid">
                    <!-- Logo -->
                    <div class="d-flex align-items-center">
                        <a asp-controller="Accueil" asp-action="Index">
                            <img class="mx-auto" src="~/lib/images/logo_cegep.png" width="50%" alt="Logo du cégep de l'outaouais.">
                        </a>
                    </div>

                    <!-- Boutton hamburger -->
                    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarToggleExternalContent"
                            aria-controls="navbarToggleExternalContent" aria-expanded="false" aria-label="Toggle navigation">
                        <span class="navbar-toggler-icon"></span>
                    </button>

                    <!-- Liens de navigations -->
                    <div class="collapse navbar-collapse" id="navbarToggleExternalContent">
                        <ul class="navbar-nav mr-auto my-auto">
                            <li class="nav-item m-1">
                                <a asp-controller="Inscription" asp-action="Index" class="btn btn-outline-light">
                                    Inscription cours
                                </a>
                            </li>
                            <li class="nav-item m-1">
                                <a asp-controller="Cours" asp-action="Liste" class="btn btn-outline-light">
                                    Cours
                                </a>
                            </li>
                            <li class="nav-item m-1">
                                <a asp-controller="Local" asp-action="Liste" class="btn btn-outline-light">
                                    Locaux
                                </a>
                            </li>
                            <li class="nav-item m-1">
                                <a asp-controller="Enseignant" asp-action="Liste" class="btn btn-outline-light">
                                    Enseignants
                                </a>
                            </li>

                            <partial name="_LoginPartial" />
                        </ul>
                    </div>
                </div>
            </nav>
        </div>
    </header>
    
    <div class="container">
        <main role="main" class="pb-3 mt-3 ">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted fixed-bottom">
        <div class="container my-2 mx-1">
            &copy; 2023 - GestionHoraire - Créé par <u>Samir El Haddaji</u> et <u>Jean-François Gamache</u>
        </div>
    </footer>
    <!-- Scripts: Hamburger et autre -->
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("JQueryValidationScripts", required: false)
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>