GestionHoraire/GestionHoraire/Models/Class/Client.cs
using GestionHoraire.Models;
using Microsoft.AspNetCore.Identity;
using System.ComponentModel;

namespace GestionHoraire.Models
{
    public class Clients
    {
        public int Id { get; set; }
        public string UserID { get; set; }
        [DisplayName("Prenom")]
        public string Prenom { get; set; }
        [DisplayName("Nom")]
        public string Nom { get; set; }
        [DisplayName("Liste des cours")]
        public ICollection<InscriptionPanier> ListeCours { get; set; }
    }
}

GestionHoraire/GestionHoraire/Controllers/ClientController.cs
//@Author: samir
using Microsoft.AspNetCore.Mvc;
using GestionHoraire.Models;
using Microsoft.AspNetCore.Authorization;
using System.Security.Claims;

namespace GestionHoraire.Controllers
{
    public class ClientController : Controller
    {
        IClientRepository _clientRepository;

        public ClientController(IClientRepository clientRepository)
        {
            _clientRepository = clientRepository;
        }

        [HttpGet]
        public ViewResult Connexion()
        {
            ViewData["Title"] = "Connexion";
            return View();
        }

        [HttpGet]
        public ViewResult Inscription()
        {
            ViewData["Title"] = "Inscription";
            return View();
        }

        [HttpGet]
        public ViewResult Ajouter()
        {
            return View();
        }

        [HttpPost]
        public IActionResult Ajouter(Clients client)
        {
            _clientRepository.Ajouter(client);
            return RedirectToAction("Index", "Accueil");
        }

        [HttpGet]
        public ViewResult Details()
        {
            var userId = User.FindFirstValue(ClaimTypes.NameIdentifier);

            Clients client = _clientRepository.ListeClients.FirstOrDefault(c => c.UserID == userId);
            return View(client);
        }
    }
}

GestionHoraire/GestionHoraire/Views/Client/Ajouter.cshtml
@{
    var userId = TempData["UserId"];
}

@using GestionHoraire.Models
@model Clients

<h1 class="text-white text-center">Veuillez entrer des informations supplémentaires</h1>


<div class="row text-white m-4">
    <form asp-controller="Client" asp-action="Ajouter" method="post">

        <div class="pb-3">
            <label asp-for="UserID" class="form-label">Id de l'usager</label>
            <input asp-for="UserID" class="form-control" type="text" value="@userId" readonly>
        </div>

        <div class="pb-3">
            <label asp-for="Prenom" class="form-label">Prenom</label>
            <input asp-for="Prenom" class="form-control" type="text" minlength="4" maxlength="50" placeholder="Veuillez entrer votre prenom">
            <span asp-validation-for="Prenom" class="text-danger"></span>
        </div>

        <div class="pb-3">
            <label asp-for="Nom" class="form-label">Nom</label>
            <input asp-for="Nom" class="form-control" type="text" minlength="4" maxlength="50" placeholder="Veuillez entrer votre nom">
            <span asp-validation-for="Nom" class="text-danger"></span>
        </div>

        <button type="submit" class="btn btn-primary btn-block">Enregistrer</button>
    </form>
    @section JQueryValidationScripts {
        <partial name="_ValidationScriptsPartial" />
    }
 </div>